CREATE TABLE `author` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '作者ID',
  `name` VARCHAR(50) NOT NULL COMMENT '名前',
  `site_url` VARCHAR(200) DEFAULT NULL COMMENT 'サイトURL',
  `twitter_account` VARCHAR(20) DEFAULT NULL COMMENT 'Twitterアカウント',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP '更新日時',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8_unicode_ci COMMENT='作者';
