CREATE TABLE `manga` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '漫画ID',
  `title` VARCHAR(50) NOT NULL COMMENT 'タイトル',
  `title_short` VARCHAR(20) DEFAULT NULL COMMENT 'タイトル略称',
  `author` VARCHAR(50) NOT NULL COMMENT '作者',
  `author_id` INT(11) UNSIGNED DEFAULT NULL COMMENT '作者ID',
  `original_author` VARCHAR(50) DEFAULT NULL COMMENT '原作',
  `original_author_id` INT(11) UNSIGNED DEFAULT NULL COMMENT '原作ID',
  `support_author` VARCHAR(50) DEFAULT NULL COMMENT 'サポート作者',
  `support_author_id` INT(11) UNSIGNED DEFAULT NULL COMMENT 'サポート作者ID',
  `magazine_id` INT(11) UNSIGNED DEFAULT NULL COMMENT '雑誌ID',
  `public_url` VARCHAR(200) DEFAULT NULL COMMENT '公式URL',
  `twitter_account` VARCHAR(20) DEFAULT NULL COMMENT 'Twitterアカウント',
  `twitter_hash_tag` VARCHAR(20) DEFAULT NULL COMMENT 'Twitterハッシュタグ',
  `target_sex` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '対象性別',
  `release_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '連載状況',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP '更新日時',
  PRIMARY KEY (`id`),
  INDEX `idx_manga_01` (`title`),
  INDEX `idx_manga_02` (`author_id`),
  INDEX `idx_manga_03` (`original_author_id`),
  INDEX `idx_manga_04` (`magazine_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8_unicode_ci COMMENT='漫画';
