CREATE TABLE `retension_info` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '保持データID',
  `magazine_id` INT(11) UNSIGNED NOT NULL COMMENT '雑誌ID',
  `year` SMALLINT(3) NOT NULL COMMENT '年',
  `month` TINYINT(2) NOT NULL COMMENT '月',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP '更新日時',
  PRIMARY KEY (`id`),
  INDEX `idx_retension_info_01` (`magazine_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='保持データの情報';
